### ISSUE TITLE
Error on second input #java

### ISSUE THREAD

**Issue by CoconutComputerClub** [CoconutComputerClub/gen-x-learning#1]
@shegi-developer 
Ketika menginput yang bukan angka pada inputan kedua error muncul
![photo_2020-03-23_16-55-30](https://user-images.githubusercontent.com/61926515/77299251-24656b80-6d27-11ea-8951-b354d3b5fb14.jpg)

**Comment by shegi-developer** [comment]
yeahh ready kak I fixed the error :)

**Comment by CoconutComputerClub** [comment]
good job 

![Screenshot from 2020-03-23 22-17-52](https://user-images.githubusercontent.com/61926515/77326166-61942280-6d54-11ea-98a4-8b32a9a1e847.png)
